CREATE DATABASE replDATABASE;
CREATE USER replREPLUSER WITH REPLICATION ENCRYPTED PASSWORD 'replPASS';
\c replDATABASE
CREATE TABLE phones(
    id_phone SERIAL PRIMARY KEY,
    phone VARCHAR(30)
);
CREATE TABLE emails(
    id_email SERIAL PRIMARY KEY,
    email VARCHAR(255)
);